resources:
- name: headless-browser-image-repo
  type: git
  icon: github
  source:
    uri: git@github.com:EngineerBetter/pcfops-docker.git
    branch: master
    private_key: ((github_private_key))

- name: oci-task-image
  type: registry-image
  icon: docker
  source:
    repository: vito/oci-build-task

- name: headless-fly-image
  type: registry-image
  icon: docker
  source:
    username: ((dockerhub_user))
    password: ((dockerhub_password))
    repository: engineerbetter/headless-fly-image

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: headless-browser-image-repo
    trigger: true
  - set_pipeline: self
    file: headless-browser-image-repo/pipeline.yml

- name: build-image
  serial: true
  plan:
  - in_parallel:
    - get: headless-browser-image-repo
      trigger: true
      passed: [set-pipeline]
    - get: oci-task-image
  - task: build-image
    privileged: true
    image: oci-task-image
    config:
      platform: linux
      inputs:
      - name: headless-browser-image-repo
        path: .
      outputs:
      - name: image
      run:
        path: build
  - put: headless-fly-image
    params: {image: image/image.tar}
