resources:
- name: headless-browser-image-repo
  type: git
  icon: github
  source:
    uri: git@github.com:EngineerBetter/headless_browser_image.git
    branch: master
    private_key: ((github_private_key))

- name: oci-task-image
  type: registry-image
  icon: docker
  source:
    repository: vito/oci-build-task

- name: headless-browser-image
  type: registry-image
  icon: docker
  source:
    username: ((dockerhub_user))
    password: ((dockerhub_password))
    repository: engineerbetter/headless-browser-image

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:EngineerBetter/headless_browser_image.git
    branch: version
    file: version
    private_key: ((github_private_key))
    initial_version: 0.0.0

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: headless-browser-image-repo
    trigger: true
  - set_pipeline: self
    file: headless-browser-image-repo/pipeline.yml

- name: build-image
  serial: true
  plan:
  - in_parallel:
    - get: headless-browser-image-repo
      trigger: true
      passed: [set-pipeline]
    - get: oci-task-image
    - get: version
      params:
        bump: patch
  - task: build-image
    privileged: true
    image: oci-task-image
    config:
      platform: linux
      inputs:
      - name: headless-browser-image-repo
        path: .
      outputs:
      - name: image
      run:
        path: build
  - put: headless-browser-image
    params:
      image: image/image.tar
      additional_tags: version/version
  - put: version
    params:
      file: version/version
